/** Client-safe re-exports of seeded engine data (no server secrets). */

export const SEED_EVENTS = [
  {
    time: "09:42:18",
    agent: "Finance Copilot",
    tool: "send_to_workspace",
    path: "PDF → Decision → External API",
    status: "blocked" as const,
    label: "INTERVENE",
    confidence: "94%",
  },
  {
    time: "09:41:05",
    agent: "HR Assistant",
    tool: "read_employee_file",
    path: "User → HR DB → Summary",
    status: "allowed" as const,
    label: "ALLOW",
    confidence: "99%",
  },
  {
    time: "09:38:44",
    agent: "Operations Agent",
    tool: "export_document",
    path: "Email → Agent → Unknown Drive",
    status: "verify" as const,
    label: "VERIFY",
    confidence: "81%",
  },
  {
    time: "09:35:12",
    agent: "Support Agent",
    tool: "search_knowledge",
    path: "Ticket → KB → Response",
    status: "allowed" as const,
    label: "ALLOW",
    confidence: "98%",
  },
  {
    time: "09:31:27",
    agent: "Procurement AI",
    tool: "invoke_vendor_api",
    path: "Web → Tool → Vendor API",
    status: "blocked" as const,
    label: "RESTRICT",
    confidence: "89%",
  },
  {
    time: "09:28:09",
    agent: "Finance Copilot",
    tool: "query_database",
    path: "User → Finance DB → Chart",
    status: "allowed" as const,
    label: "ALLOW",
    confidence: "97%",
  },
  {
    time: "09:22:33",
    agent: "Legal Reviewer",
    tool: "share_document",
    path: "Contract → Agent → Team Space",
    status: "verify" as const,
    label: "VERIFY",
    confidence: "76%",
  },
]

export const SEED_FINGERPRINTS = [
  {
    id: "X-CFS-001",
    title: "مسار تسريب بيانات عبر تعليمات غير موثوقة",
    desc: "تأثير خارجي يغيّر قرار الوكيل ثم يستغل أداة مصرحاً بها لإرسال بيانات حساسة.",
    tags: ["مصدر غير موثوق", "تأثير قرار", "بيانات حساسة", "وجهة خارجية"],
    invariants: ["مصدر غير موثوق", "تأثير قرار", "بيانات حساسة", "وجهة خارجية"],
    environment: "dev" as const,
    matches: 14,
    confidence: "94%",
    date: "18 سبتمبر 2026",
  },
  {
    id: "X-CFS-002",
    title: "تصعيد صلاحيات غير مباشر",
    desc: "طلب طبيعي ظاهرياً يؤدي إلى توسيع نطاق الأداة خارج متطلبات المهمة.",
    tags: ["صلاحية مرتفعة", "استدعاء أداة خارج النطاق"],
    invariants: ["صلاحية مرتفعة", "استدعاء أداة خارج النطاق"],
    environment: "enterprise" as const,
    matches: 7,
    confidence: "88%",
    date: "17 سبتمبر 2026",
  },
  {
    id: "X-CFS-003",
    title: "تسميم ذاكرة وكيل",
    desc: "إدخال غير موثوق يستقر في الذاكرة ويؤثر في قرارات لاحقة ضمن سياق جديد.",
    tags: ["تسميم ذاكرة", "انتقال سياق", "تعليمات خفية"],
    invariants: ["تسميم ذاكرة", "انتقال سياق", "تعليمات خفية"],
    environment: "cloud" as const,
    matches: 5,
    confidence: "91%",
    date: "16 سبتمبر 2026",
  },
]
